### PR TITLE
Merges minutes of 16-12-2022 meeting

### PR DESCRIPTION
**Pull request by DaniMori**

### CODE REVIEW

**Comment by DaniMori** [comment]
@robertomediavilla you can take over and then click on "Ready for review" to ask the rest for reviews. As I'm the author of the PR you won't be able to assign me as a reviewer but I can review if you comment "@calling" me.

**Review by Cristrinaranjus — APPROVED** [review]
Great job!!

**Review by robertomediavilla — APPROVED** [review]
Looks perfect. Thanks a lot @DaniMori

**Review by JesusSierralaya — APPROVED** [review]

**Review by DaniMori — COMMENTED** [review]
Good to go then on my side @robertomediavilla . Do a "merge commit" please!

**Pull request merged**
