### PR TITLE
Fills in "Description" section

### PR DESCRIPTION
**Pull request by DaniMori**
This first version tries to respond to the questions in the three bullet points in the prompt. It has been diffcult to adhere to the word count limit. Right now it's very tight I'm afraid, please take it into account when making suggestions!

### CODE REVIEW

**Comment by DaniMori** [comment]
@Cristrinaranjus and @Leafrancia I have put aside a few lines I have dropped that may be useful for the "Outputs" and "Reusability" sections, please check them out:

https://github.com/CCOMS-UAM/yos-award/blob/30d55b2a4996eb9b75e6b918e48ec32a2b9fd824/output/Form.md?plain=1#L59

https://github.com/CCOMS-UAM/yos-award/blob/30d55b2a4996eb9b75e6b918e48ec32a2b9fd824/output/Form.md?plain=1#L66

**Comment by robertomediavilla** [comment]
Section reviewed. Commit made and pushed to this branch. Currently 374 words and, in my view, ready to submit

**Comment by robertomediavilla** [comment]
I closed pull request by mistake!

**Review by DaniMori — COMMENTED** [review]
This looks great @robertomediavilla !

**Comment by DaniMori** [comment]
Guys, please review and (if you think it's ok) approve!

**Review by Cristrinaranjus — APPROVED** [review]

**Review by robertomediavilla — APPROVED** [review]

**Review by Cristrinaranjus — APPROVED** [review]

**Comment by DaniMori** [comment]
@JesusSierralaya and @Leafrancia your approval is pending! ;)

**Comment by DaniMori** [comment]
@JesusSierralaya please approve asap, thanks!!

**Review by JesusSierralaya — APPROVED** [review]

**Pull request merged**
