### PR TITLE
Revert "Fills-in reusability section"

### PR DESCRIPTION
**Pull request by DaniMori**
Reverts CCOMS-UAM/yos-award#8

### CODE REVIEW

**Comment by DaniMori** [comment]
@Cristrinaranjus sorry, this PR should be reverted; the PR should actually merge branch `drafting/reusability` to `drafting/tempalte-fillin`. Apologies that I didn't notice the base branch was set to `main`.

**Comment by Cristrinaranjus** [comment]
> 

I think I don't know exactly how to revert a closed PR. How can it be done?

**Comment by DaniMori** [comment]
Using the "revert" functionality has automatically created a new branch with the merge commit reverted and a PR to merge to "main".

Not sure if it's worth the effort, so we may not do it; let's discuss this in today's meeting.

**Review by robertomediavilla — APPROVED** [review]

**Comment by DaniMori** [comment]
We have agreed to NOT revert this commit, and rebase the branch `feature/teplate-fillin` instead

**Pull request closed without merging**
